"""add users, user_profiles, hauler_profiles

Revision ID: 1befd19256c6
Revises: 
Create Date: 2026-05-24 17:53:31.197674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1befd19256c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('hauler_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_type', sa.Enum('pickup', 'pickup_with_trailer', 'flatbed', 'box_truck', 'cargo_van', 'semi', 'other', name='vehicletype'), nullable=False),
    sa.Column('vehicle_make', sa.String(length=64), nullable=True),
    sa.Column('vehicle_model', sa.String(length=64), nullable=True),
    sa.Column('vehicle_year', sa.Integer(), nullable=True),
    sa.Column('max_weight_lbs', sa.Integer(), nullable=True),
    sa.Column('max_length_ft', sa.Float(), nullable=True),
    sa.Column('max_width_ft', sa.Float(), nullable=True),
    sa.Column('max_height_ft', sa.Float(), nullable=True),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('insurance_doc_url', sa.String(length=1024), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('shipper_enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('hauler_enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('stripe_account_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('hauler_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
