"""add loads table

Revision ID: 5d55ac998b46
Revises: 1befd19256c6
Create Date: 2026-05-24 18:00:04.600746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d55ac998b46'
down_revision: Union[str, Sequence[str], None] = '1befd19256c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipper_id', sa.String(length=36), nullable=False),
    sa.Column('hauler_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('photo_urls', sa.JSON(), nullable=False),
    sa.Column('weight_lbs', sa.Integer(), nullable=False),
    sa.Column('length_ft', sa.Float(), nullable=True),
    sa.Column('width_ft', sa.Float(), nullable=True),
    sa.Column('height_ft', sa.Float(), nullable=True),
    sa.Column('pickup_address', sa.String(length=255), nullable=False),
    sa.Column('pickup_city', sa.String(length=128), nullable=False),
    sa.Column('pickup_state', sa.String(length=32), nullable=False),
    sa.Column('pickup_zip', sa.String(length=16), nullable=False),
    sa.Column('pickup_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pickup_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dropoff_address', sa.String(length=255), nullable=False),
    sa.Column('dropoff_city', sa.String(length=128), nullable=False),
    sa.Column('dropoff_state', sa.String(length=32), nullable=False),
    sa.Column('dropoff_zip', sa.String(length=16), nullable=False),
    sa.Column('dropoff_by', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_distance_miles', sa.Float(), nullable=False),
    sa.Column('urgency', sa.Enum('standard', 'express', name='urgency'), nullable=False),
    sa.Column('calculated_price_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'posted', 'accepted', 'picked_up', 'in_transit', 'delivered', 'cancelled', name='loadstatus'), server_default='posted', nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hauler_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipper_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loads_dropoff_city'), 'loads', ['dropoff_city'], unique=False)
    op.create_index(op.f('ix_loads_dropoff_state'), 'loads', ['dropoff_state'], unique=False)
    op.create_index(op.f('ix_loads_hauler_id'), 'loads', ['hauler_id'], unique=False)
    op.create_index(op.f('ix_loads_pickup_city'), 'loads', ['pickup_city'], unique=False)
    op.create_index(op.f('ix_loads_pickup_state'), 'loads', ['pickup_state'], unique=False)
    op.create_index(op.f('ix_loads_shipper_id'), 'loads', ['shipper_id'], unique=False)
    op.create_index(op.f('ix_loads_status'), 'loads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loads_status'), table_name='loads')
    op.drop_index(op.f('ix_loads_shipper_id'), table_name='loads')
    op.drop_index(op.f('ix_loads_pickup_state'), table_name='loads')
    op.drop_index(op.f('ix_loads_pickup_city'), table_name='loads')
    op.drop_index(op.f('ix_loads_hauler_id'), table_name='loads')
    op.drop_index(op.f('ix_loads_dropoff_state'), table_name='loads')
    op.drop_index(op.f('ix_loads_dropoff_city'), table_name='loads')
    op.drop_table('loads')
    # ### end Alembic commands ###
