"""add booking_events table

Revision ID: 9caef0c549f9
Revises: 5d55ac998b46
Create Date: 2026-05-24 18:04:35.273765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9caef0c549f9'
down_revision: Union[str, Sequence[str], None] = '5d55ac998b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('load_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('accepted', 'picked_up', 'in_transit', 'delivered', 'cancelled', name='bookingeventtype'), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_events_created_at'), 'booking_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_booking_events_load_id'), 'booking_events', ['load_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_events_load_id'), table_name='booking_events')
    op.drop_index(op.f('ix_booking_events_created_at'), table_name='booking_events')
    op.drop_table('booking_events')
    # ### end Alembic commands ###
